class RetrievalConst:
    MAX_SCORE_THRESHOLD = 1
    MIN_SCORE_THRESHOLD = 0
    DEFAULT_SCORE_THRESHOLD = 0.1
    DEFAULT_K = 3
    MAXIMUN_K = 10
    MINIMUM_K = 1
    STRATEGIES_CHOICES = ["base", "BCERerank"]
    DEFAULT_STRATEGY = STRATEGIES_CHOICES[0]